l08/config/routes.rb
Rails.application.routes.draw do
  get '/rules', to: 'players#rules'
  get '/champions', to: 'players#champions'
  get '/home', to: 'players#home'
  get '/form', to: 'players#form'
  root 'players#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

l08/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

l08/app/models/player.rb
class Player < ApplicationRecord

end

l08/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

l08/app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def rules
  end

  def champions
    @players = Player.all
  end

  def home
    @players = Player.where.not(name: nil)
  end

  def form
    @player = Player.new
    @player.name = params[:name]
    @player.death_year = params[:death_year].to_i
    @player.birth_year = params[:birth_year].to_i
    @player.save
    redirect_to root_path
  end
end

l08/app/helpers/application_helper.rb
module ApplicationHelper
  def title(title)
    content_for(:title) {title}
  end
end

l08/app/helpers/players_helper.rb
module PlayersHelper
end

l08/app/views/layouts/_navigation.html.erb
<ul class="menu">
  <li>
    <%= link_to 'Home', home_path %>
  </li>
  <li>
    <%= link_to 'Rules', rules_path %>
  </li>
  <li>
    <%= link_to 'Champions', champions_path %>
  </li>
</ul>

l08/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= content_for?(:title) ? content_for(:title) : "My chess app"%></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= content_for(:test) %>
    <%= render 'layouts/navigation' %>
    <%= yield %>
  </body>
</html>

l08/app/views/players/champions.html.erb
<h1>Players#champions</h1>
<p>Find me in app/views/players/champions.html.erb</p>
<% content_for(:title) {"Champions page"} %>

<% @players.each do |p| %>
  <h4><%= p.name %></h4>
  <p> <%= "#{p.birth_year}-#{p.death_year}" %></p>
<% end %>


<form action="/form">
  <input type="text" name="name">
  <input type="text" name="birth_year">
  <input type="text" name="death_year">
  <input type="submit">
</form>

l08/app/views/players/home.html.erb
<% content_for(:title) {"Home page"} %>
<h1>Players#index</h1>
<p>Find me in app/views/players/index.html.erb</p>
<div class="block">
  <div class="board">
    <table>
      <tr>
        <td>&#9820;</td>
        <td>&#9822;</td>
        <td>&#9821;</td>
        <td>&#9819;</td>
        <td>&#9818;</td>
        <td>&#9821;</td>
        <td>&#9822;</td>
        <td>&#9820;</td>
      </tr>
      <tr>
        <% 8.times do %>
          <td>&#9823;</td>
        <% end %>
      </tr>
      <% 4.times do %>
        <tr>
          <% 8.times do %>
            <td></td>
          <% end %>
        </tr>
      <% end %>
      <tr>
        <% 8.times do %>
          <td>&#9817;</td>
        <% end %>
      </tr>
      <tr>
        <td>&#9814;</td>
        <td>&#9816;</td>
        <td>&#9815;</td>
        <td>&#9813;</td>
        <td>&#9812;</td>
        <td>&#9815;</td>
        <td>&#9816;</td>
        <td>&#9814;</td>
      </tr>
    </table>
  </div>
  <div class="player-list">
    <ol>
      <% @players.each do |p| %>
        <li>
          <%= "#{p.name} #{p.lastname}" %>
          <span class="hidden"> <%= "#{p.birth_year} - #{p.death_year}" %> </span>
        </li>
      <%end %>
    </ol>
  </div>
</div>

l08/app/views/players/rules.html.erb
<% title('Rules page') %>
<h1>Players#rules</h1>
<p>Find me in app/views/players/rules.html.erb</p>
<% content_for(:test) do %>
  <ul>
    <li> Hello </li>
    <li> How </li>
    <li> Are </li>
    <li> YOU? </li>
  </ul>
<% end %>



<% content_for(:test) {"<h1> Hello </h1>"} %>